### ISSUE TITLE
Criar página "Equipe"

### ISSUE THREAD

**Issue by diogomoreira** [recursivejr/recursivejr.github.io#4]
Como uma sugestão, eu acho que seria melhor criar uma página "Equipe" para separar da página "Quem somos".

Nela cada um poderia inclusive escrever um texto sobre si mesmo, junto com a foto e as formas de ser contactado (email, github, etc).

**Comment by douglasgabriel** [comment]
Ótima ideia, tentei manter o padrão do site, mas realmente não ficou legal, uma vez que tá quebrando bastante a responsividade
